export const LANDING_MARKER = '<!-- generated by github-card-to-calendar -->';

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Embeds a value in an inline <script>; JSON-encodes and neutralises "</script>" / "<!--". */
function jsString(value: string): string {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

export function renderLandingPage(
  calendarName: string,
  calendarDescription: string,
  eventCount: number,
  icsFileName: string
): string {
  const name = escapeHtml(calendarName);
  const description = escapeHtml(calendarDescription);
  const fileAttr = encodeURI(icsFileName).replace(/"/g, '%22');

  return `<!DOCTYPE html>
${LANDING_MARKER}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${name}</title>
  <style>
    :root {
      --bg: #0d1117;
      --card-bg: #161b22;
      --border: #30363d;
      --text: #c9d1d9;
      --heading: #f0f6fc;
      --muted: #8b949e;
      --input-bg: #0d1117;
      --btn-secondary-bg: #21262d;
      --btn-secondary-hover: #30363d;
      --shadow: rgba(0,0,0,0.4);
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #f6f8fa;
        --card-bg: #ffffff;
        --border: #d0d7de;
        --text: #24292f;
        --heading: #1f2328;
        --muted: #57606a;
        --input-bg: #f6f8fa;
        --btn-secondary-bg: #f6f8fa;
        --btn-secondary-hover: #eaeef2;
        --shadow: rgba(140,149,159,0.3);
      }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      margin: 0;
      padding: 1.5rem;
      box-sizing: border-box;
    }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 2.5rem;
      max-width: 520px;
      width: 100%;
      box-shadow: 0 8px 24px var(--shadow);
    }
    h1 {
      color: var(--heading);
      margin: 0 0 0.5rem;
      font-size: 1.75rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    p {
      color: var(--text);
      line-height: 1.5;
      margin: 0.5rem 0 1.5rem;
    }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.6rem;
      background: #238636;
      color: #fff;
      border-radius: 20px;
      font-size: 0.85rem;
      font-weight: 600;
      margin-bottom: 1.5rem;
    }
    .actions {
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }
    .btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      padding: 0.75rem 1.25rem;
      border-radius: 6px;
      font-weight: 600;
      text-decoration: none;
      transition: background 0.2s;
      cursor: pointer;
      border: none;
      font-size: 1rem;
    }
    .btn-primary {
      background: #238636;
      color: white;
    }
    .btn-primary:hover {
      background: #2ea043;
    }
    .btn-secondary {
      background: var(--btn-secondary-bg);
      color: var(--heading);
      border: 1px solid var(--border);
    }
    .btn-secondary:hover {
      background: var(--btn-secondary-hover);
    }
    .url-box {
      margin-top: 1.5rem;
      background: var(--input-bg);
      border: 1px solid var(--border);
      border-radius: 6px;
      padding: 0.75rem;
      font-family: monospace;
      font-size: 0.85rem;
      word-break: break-all;
      user-select: all;
    }
    .footer {
      margin-top: 2rem;
      font-size: 0.8rem;
      color: var(--muted);
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>📅 ${name}</h1>
    <p>${description}</p>
    <div class="badge">${eventCount} Scheduled Events</div>
    <div class="actions">
      <a id="google-btn" href="#" class="btn btn-primary" target="_blank" rel="noopener">Add to Google Calendar</a>
      <a id="webcal-btn" href="${fileAttr}" class="btn btn-secondary">Download / Subscribe (.ics)</a>
    </div>
    <div class="url-box" id="ics-url">Loading calendar URL...</div>
    <div class="footer">Synced via GitHub Actions</div>
  </div>
  <script>
    const icsUrl = new URL(${jsString(encodeURI(icsFileName))}, window.location.href).href;
    document.getElementById('ics-url').textContent = icsUrl;
    // Google Calendar render URL requires webcal or http/https link encoded
    const webcalUrl = icsUrl.replace(/^https?:\\/\\//, 'webcal://');
    document.getElementById('google-btn').href = 'https://calendar.google.com/calendar/render?cid=' + encodeURIComponent(webcalUrl);
    document.getElementById('webcal-btn').href = webcalUrl;
  </script>
</body>
</html>`;
}
